### ISSUE TITLE
Request for Proof of Functionality

### ISSUE THREAD

**Issue by syarfandi** [yukkerike/dex_feature_enabler#1]
This seems quite difficult to believe it will work. Please provide evidence by including a YouTube video as proof, and embed the video in the README as well.

**Comment by yukkerike** [comment]
The instructions can be found on the xda. This script automatically applies the edits as described. I do not see here anything extraordinary or requiring proofs. SEC_FLOATING_FEATURE_COMMON_CONFIG_DEX_MODE is a well-known key in community.
