### ISSUE TITLE
Knox and warranty?

### ISSUE THREAD

**Issue by zlndr** [yukkerike/dex_feature_enabler#2]
HELLO! 
Does this app defeat Knox protection and Samsung warranty (or Magisk and the bootloader?!) 
Thanks for the answer! 
Good day!

**Comment by yukkerike** [comment]
Hey! It trips the Knox bit since there's no way to install Magisk without unlocking the bootloader.

**Comment by zlndr** [comment]
> Hey! It trips the Knox bit since there's no way to install Magisk without unlocking the bootloader.

Thanks for the information!
